# Handling errors 处理错误

Whilst it is easy to create flows that do the right thing when everything works, it is also important to think about what could go wrong.
虽然在一切正常的情况下，很容易创建做正确事情的流程，但考虑可能出错的地方也很重要。

For example, if the flow interacts with an external database or API, what happens if it stops responding to requests? Or what if the MQTT nodes lose their connection to a broker?
例如，如果流与外部数据库或API交互，如果它停止响应请求会发生什么？或者，如果MQTT节点失去了与代理的连接怎么办？

Error handling in any application is essential to ensure these sorts of events are handled properly. What it means to handle the error will depend on the requirements of the application. You may want to try an action that failed, or trigger a separate alert, or maybe the error is an entirely expected event that is just another part of the application logic.
任何应用程序中的错误处理对于确保正确处理这类事件都是必不可少的。处理错误的含义取决于应用程序的要求。您可能想尝试一个失败的操作，或者触发一个单独的警报，或者错误是一个完全预期的事件，只是应用程序逻辑的另一部分。

Node-RED provides two ways for a node to report an error. It can either just write a message to the log or it can notify the runtime of the error and cause a flow to be triggered.
Node-RED为节点提供了两种报告错误的方法。它可以只向日志中写入一条消息，也可以将错误通知给运行时并触发流。

If the error is only written to the log, you will see the message in the Debug sidebar and log output, but you will not be able to create a flow to handle it. These are [uncatchable errors](https://nodered.org/docs/user-guide/handling-errors#uncatchable-errors).
如果错误只写入日志，您将在工具栏和日志输出中看到消息，但您将无法创建流来处理它。这些是[无法捕获的错误](https://nodered.org/docs/user-guide/handling-errors#uncatchable-errors)。

If it does notify the runtime properly, then it is a [catchable error](https://nodered.org/docs/user-guide/handling-errors#catchable-errors) that can be used to trigger an error-handling flow.
如果它确实正确地通知了运行库，那么它就是一[个可捕捉的错误](https://nodered.org/docs/user-guide/handling-errors#catchable-errors) 其可用于触发错误处理流。

There is a third sort of error that can cause the Node-RED runtime to shutdown. These [`uncaughtException` errors](https://nodered.org/docs/user-guide/handling-errors#uncaughtexception-errors) cannot be handled in the flow and are caused by bugs in nodes.
还有第三种错误会导致Node-RED运行时关闭。这些 [`uncaughtException`错误](https://nodered.org/docs/user-guide/handling-errors#uncaughtexception-errors)无法在流中处理，并且是由节点中的错误引起的。

This guide describes each of these error types in more detail and shows what can be done to handle them. It also looks at how the Status events of a node can be used to create flows that [handle unexpected events](https://nodered.org/docs/user-guide/handling-errors#handling-status-changes).
本指南更详细地描述了这些错误类型中的每一种，并展示了可以采取哪些措施来处理它们。它还研究了如何使用节点的Status事件来创建[处理意外事件](https://nodered.org/docs/user-guide/handling-errors#handling-status-changes)的流。

### Logging errors 记录错误

When a node logs an error, it will appear in the Debug sidebar.
当一个节点记录错误时，它将出现在工具栏中。

![Error message in the Debug sidebar](https://nodered.org/docs/user-guide/images/error_debug.png)

Error message in the Debug sidebar
错误消息在工具栏

This shows the error message, the date/time of the error, and the node that logged the error. As with other Debug messages, hovering over it will highlight the node in the workspace. If it isn’t in the current view, then clicking on the node’s name in the top corner will reveal it in the workspace.
这将显示错误消息、错误的日期/时间以及记录错误的节点。与其他消息一样，将鼠标悬停在它上面将突出显示工作区中的节点。如果它不在当前视图中，那么单击左上角的节点名称将在工作区中显示它。

### Catchable errors 可捕捉错误

If a node notifies the runtime of an error then the Catch node can be used to create a flow to handle it.
如果一个节点通知运行时一个错误，那么Catch节点可以用来创建一个流来处理它。

![Catch node](https://nodered.org/docs/user-guide/images/error_catch.png)

Catch node 捕捉节点

If an error is caught by a Catch node, it *will not* be logged to the Debug sidebar.
如果Catch节点捕获到错误，*则不会*将其记录到工具栏。

The message sent by the Catch will be the message provided by the node reporting the error. This message will have an `error` property set that provides information about the error:
Catch发送的消息将是报告错误的节点提供的消息。此消息将具有一个`错误`属性集，该属性提供有关错误的信息：

```
{
    "topic": ...,
    "payload": ...,
    "error": {
        "message": "An error",
        "source": {
            "id": "2e25823d.fa3f7e",
            "type": "function",
            "name": "My Function",
            "count": 1
        }
    }
}
```

The properties of `msg.error` are:
`msg.error`的属性是：

- ```plaintext
  msg.error
  ```

  :    

  
  `msg.error`：

  - `message` - the error message
    `消息`-错误消息

  - ```plaintext
    source
    ```

     \- information about the node logging the error:        

    
    `source`-有关记录错误的节点的信息：

    - `id` - the source node id
      `id`-源节点id
    - `type` - the type of the source node
      `type`-源节点的类型
    - `name` - the name, if set, of the source node
      `name`-源节点的名称（如果已设置）
    - `count` - how many times *this* message has been thrown by *this* node. This property is used by the runtime to detect messages stuck in a loop - where they are passed back to the source node which then logs the error again, and so on. The runtime will allow a message to loop 9 times before logging another, uncatchable, error to break the loop. Deleting this property will disable the check.
      `count`-*此* 消息被*此*节点抛出的次数。运行时使用此属性来检测陷入循环的消息-在循环中，消息被传递回源节点，然后源节点再次记录错误，依此类推。运行时将允许消息循环9次，然后记录另一个无法捕获的错误，以打破循环。删除此属性将禁用检查。

If the message already had a `msg.error` property when the node reported the error, that property will be moved to `msg._error`.
如果消息在节点报告错误时已经具有`msg.error`属性，则该属性将被移动到`msg._错误`.

By default, the Catch node is configured to be triggered by all nodes on the same tab in the editor, but it can also be configured to target specific nodes on the tab.
默认情况下，Catch节点配置为由编辑器中同一选项卡上的所有节点触发，但也可以将其配置为针对选项卡上的特定节点。

If you have two Catch nodes on the same tab and they both target the same node, then they will both be triggered by any errors reported by that node.
如果在同一个选项卡上有两个Catch节点，并且它们都指向同一个节点，那么它们都将被该节点报告的任何错误触发。

If a Catch node is configured to be triggered by all nodes, it can also be configured to only trigger on errors that have not already been caught by another Catch node. This allows you to create error handling flows that target specific nodes and also have an error handler that will catch “everything else”.
如果Catch节点配置为由所有节点触发，则也可以将其配置为仅在其他Catch节点尚未捕获的错误时触发。这允许您创建针对特定节点的错误处理流，并且还具有将捕获“其他所有内容”的错误处理程序。

#### Errors in subflows 子流中的错误

If an error is logged from inside a subflow, the runtime will first check for any Catch nodes inside the subflow. If there are none there, the error will propagate up to the flow containing the subflow instance.
如果从子流内部记录错误，则运行库将首先检查子流内部的任何Catch节点。如果没有，错误将传播到包含子流实例的流。

### Uncatchable errors 无法捕捉的错误

These are the errors a node writes to the log without notifying the runtime properly. They cannot be handled using the Catch node.
这些是节点在没有正确通知运行时的情况下写入日志的错误。无法使用Catch节点处理它们。

The node *might* provide alternative ways for handling the error. For example, by updating its status property (which can be monitored with the Status node). It may send a message as normal but with some additional property set to indicate the error.
节点*可能*提供处理错误的替代方法。例如，通过更新其状态属性（可以使用状态节点进行监视）。它可以正常发送消息，但设置了一些附加属性来指示错误。

You may want to contact the node’s author to see if it can be updated to log the error properly.
您可能需要联系节点的作者，查看是否可以更新它以正确记录错误。

### `uncaughtException` errors `uncaughtException`错误

These are a particular type of node.js error that can occur when a Node fails to properly handle an internal error. They cause the entire Node-RED runtime to shutdown as that is the only safe thing to do.
这是一种特殊类型的node.js错误，当Node无法正确处理内部错误时可能会发生。它们会导致整个Node-RED运行时关闭，因为这是唯一安全的做法。

It may sound extreme, but here is what the [node.js documentation](https://nodejs.org/api/process.html#process_warning_using_uncaughtexception_correctly) says about it:
这听起来可能很极端，但[node.js文档](https://nodejs.org/api/process.html#process_warning_using_uncaughtexception_correctly)是这样说的：

> Attempting to resume normally after an uncaught exception can be similar to  pulling out the power cord when upgrading a computer. Nine out of ten  times, nothing happens. But the tenth time, the system becomes  corrupted.
> 尝试在未捕获的异常之后恢复正常，类似于在升级计算机时拔出电源线。十次有九次，什么都没发生。但是第十次，系统就被破坏了。

The typical cause will be that a node has kicked off an asynchronous task and that task has hit an error. A well-written node will have registered an error handler for that task, but if there isn’t one, the error will go uncaught.
典型的原因是节点启动了一个异步任务，而该任务遇到了错误。一个编写良好的节点将为该任务注册一个错误处理程序，但如果没有，错误将不会被捕获。

If you encounter this type of error then you should attempt to identify which node caused the error and raise an issue against it. This is not always easy due to the asynchronous nature of the error.
如果您遇到这种类型的错误，那么您应该尝试识别哪个节点导致错误并提出问题。由于错误的异步性质，这并不总是容易的。

The stack trace provided in the Node-RED log will provide some clues as to the nature of the asynchronous task that hit the error, which in turn may help you to identify the node at fault.
Node-RED日志中提供的堆栈跟踪将提供一些有关发生错误的异步任务的性质的线索，这反过来可以帮助您识别出错的节点。

### Handling Status Changes 处理状态更改

Not all errors conditions will appear as error events that can be caught be a Catch node. For example, the MQTT nodes losing their connection will not trigger an error, but they will trigger a change of their status.
并非所有错误条件都将显示为可以由Catch节点捕获的错误事件。例如，MQTT节点失去连接不会触发错误，但会触发其状态的更改。

Just as the Catch node can be used to handle error events, the Status node can be used to handle changes in a node’s status.
正如Catch节点可用于处理错误事件一样，Status节点可用于处理节点状态的更改。

The message sent by the Status node includes the `status` property that gives information about the status and the node that triggered the event.
Status节点发送的消息包括`status`属性，该属性提供有关状态和触发事件的节点的信息。

```
{
    "status": {
        "fill": "red",
        "shape": "ring",
        "text": "node-red:common.status.disconnected",
        "source": {
            "id": "27bbb5b1.d3eb3a",
            "type": "mqtt out"
        }
    }
}
```